# Generated by Django 3.2.13 on 2022-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_dailygame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygame',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
