# Generated by Django 3.2.13 on 2022-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_dailygame_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='steam_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
