# Generated by Django 3.2.13 on 2022-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20220604_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='steam_reviews',
            new_name='steam_num_reviews',
        ),
        migrations.AddField(
            model_name='game',
            name='steam_negative_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_positive_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_review_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_total_reviews',
            field=models.FloatField(default=0),
        ),
    ]
