# Generated by Django 3.2.13 on 2022-06-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_trigram_extension_20220618_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='steam_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
